// src/plantDatabase.js
const plantDatabase = [
    'Aloe Vera',
    'Fiddle Leaf Fig',
    'Spider Plant',
    'Basil',
    'Rosemary',
    'Pothos',
    'Peace Lily',
    'Succulent',
    'Dracaena',
    'Snake Plant',
    'Philodendron',
    'Bird of Paradise',
    'Chinese Evergreen',
    'Rubber Plant',
    'Jade Plant',
    'Monstera',
    'Orchid',
    'Calathea',
    'Lavender',
    'Chrysanthemum',
    'Daisy',
    'Petunia',
    'Maranta',
    'Hoya',
    'Cactus',
    'Geranium',
    'Clover',
    'Carnivorous Plant',
    'Coleus',
];

module.exports = plantDatabase;